name: CI

on:
  pull_request:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@02f6c237bd2518259fed6c71566509edfb3f2b74 # v4
        with:
          run_install: true

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Build
        run: pnpm run build

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Types
        run: pnpm run types

      - name: Test
        run: pnpm run test
